### PR TITLE
Next level visual fix

### PR DESCRIPTION
**Pull request by ASecondGuy**
# Description
refactoring of the scene tree.

## Type of change
- [x] Bug fix (non breaking change that fixes an issue)
- [ ] New feature (non breaking change that adds functionality)
- [ ] Tooling (non breaking change that adds functionality to the workflow)
- [x] Breaking change (fix or feature that causes existing functionality to not work as expected)

## Testing
I ran the game multiple times and opened/closed many windows/games.

# Checklist
- [x] My code follows the general style guidelines of the project
- [x] I have perfomed a self-review of my code
- [x] I have commented my code, particulary where it is unclear
- [x] My changes generate no new warnings or errors
- [x] The project compiles and runs correctly

### CODE REVIEW

**Comment by ASecondGuy** [comment]
The merge broke stuff.
I'm gonna fix it real quick.

**Comment by ASecondGuy** [comment]
It's fixed.
Everything ready to be merged.

**Comment by ASecondGuy** [comment]
@RedstoneMedia I think this is everything. Could you take a look at it?

**Comment by RedstoneMedia** [comment]
Ok so the assertion error is now fixed, and the files are named correctly.
However:
- You have way too small margins (especially in the game card)
- You added a border to things that previously haven't had one (borders aren't always bad, but it doesn't look good in this case)
- Some colors are now to dark (game card background). Menu bar background is now too light
- Second, darker color on the bottom of the game card info pop-up was removed by you
- Font size (And type) was changed for some components (not the game cards)

Currently, I don't see any other issues than this

Edit: Removing basically all margin containers (And overrides that could create these margins) sure cuts down on the complexity of the scene tree, however in this case, maybe that wasn't the best option.

**Comment by ASecondGuy** [comment]
Thanks for the feedback. 
PanelContainers have a content margin build in so MarginContainers were redundant where I removed them.
The rest is all just visual stuff.
I could improve the looks (and probably will) but I think it's better if someone with a feeling for that would do it right the first time.

**Comment by ASecondGuy** [comment]
@RedstoneMedia I went and searched for the old values. 
I can barely distinguish the 2 versions now.
I think this is good enough. Looking back I should have done this right from the start.

**Comment by ASecondGuy** [comment]
@b7g This is ready to be merged

**Comment by RedstoneMedia** [comment]
Some of the colors and margins are still not exactly right. But this is definitely better (Also thanks for ignoring this: https://github.com/ASecondGuy/Suffragium/pull/7 and then creating your own commit to the thing you said you wouldn't fix 😀)

**Comment by ASecondGuy** [comment]
> Some of the colors and margins are still not exactly right. But this is definitely better (Also thanks for ignoring this: [ASecondGuy#7](https://github.com/ASecondGuy/Suffragium/pull/7) and then creating your own commit to the thing you said you wouldn't fix 😀)

Sorry. I just saw that this morning. That's on me.

**Comment by b7g** [comment]
You are trolling me right?
I will not merge this.

GETTA YO FUXKEN BBCODE OUTTA THERE

also

In the current state it destroys the visual appearance at many places
- it has 2 links in blue, one in white
- one link does not work
- line-spacing is gone
- margins are gone at many places

**Comment by ASecondGuy** [comment]
@b7g bbcode is deactivated. (But I still not agree to this)
That one link was an oversight. Thanks for telling me.
I think I fixed the spacing and margins now.
If not please tell me exactly where they are wrong.

**Comment by RedstoneMedia** [comment]
@ASecondGuy I fixed the things you missed. The changes are in the old PR (https://github.com/ASecondGuy/Suffragium/pull/7)

**Comment by b7g** [comment]
No, I will not merge this.
It still has at least 3 visual flaws and adds unnecessary complexity with the about.gd, just so he can have a RichTextLabel for his ego.

**Comment by ASecondGuy** [comment]
> No, I will not merge this. It still has at least 3 visual flaws and adds unnecessary complexity with the about.gd, just so he can have a RichTextLabel for his ego.

Again, please tell me what visual flaws so I can fix them.
2nd. The RichTextLabel is not for my ego. It replaces like 20 or so nodes and you can edit the about text from one textfield now.
about.gd isn't even that complex and also takes on a few functions of menu.gd making that script less complex. You must admit that is an improvement.

**Comment by RedstoneMedia** [comment]
If I'm not correct please correct me, but didn't the about section consist out of multiple nodes before (Verry complex for a bit of text) ?

Using a RichTextLabel would solve that issue. (I do agree that about.gd should at least be refactored or better documented  because I have no idea what it's for)

**Comment by ASecondGuy** [comment]
> (I do agree that about.gd should at least be refactored or better documented because I have no idea what it's for)

I didn't think it was that bad. I'll improve it asap.

**Comment by b7g** [comment]
Yes, it did. And is perfectly fine, because Godot can easily handle a few thousand.
And it did work properly also.

The shitty RichTextLabel misses LINE-SPACING, it’s not like I already said that 5 hours ago.
The shitty complexity adding about.gd does not scoll precisely (as the perfectly fine few nodes do).

I will not merge this.

**Comment by ASecondGuy** [comment]
My argument isn't that Godot can handle one RTL better than 20-50 Nodes.
My argument is that this
grafik
is easier to edit and understand than this
grafik

**Comment by b7g** [comment]
Who cares when it does not work properly, I don’t care that you don’t understand it.
I care about that it looks good and that the user likes to use it.

**Comment by b7g** [comment]
The About section also does not fill the full height
the game info popup right section lost it’s white space
the game info popup lost it’s shadow
the first link still doesn’t work for me

No love in it

**Comment by ASecondGuy** [comment]
Also this "shitty RichTextLabel" has line spacing
grafik
Easily accessible with themes or theme overwrites.
This even makes Line spacing very consistent.

The link works for me. That is something we should investigate.
And I'm also sorry I missed that subtle shadow effect.
But I'm sure if you had said that sooner, I or @RedstoneMedia would have fixed that by now.

Lastly, I won't apologize for the fact that my passions don't exactly align with yours.
That might make it look like I don't put love into it but I assure you, that is what you scene tree looked like to me.

**Comment by Numenter** [comment]
Three visuals I see.

1. There is a gap between header and body
image
2. Old link color looks better (#649bff)
image
3. remove the "About Suffragium" over Report a bug
image

**Comment by Numenter** [comment]
The about bbcode text is empty. Do I look at the right place?
image
image
The normal text has no code.
Godot 3.4.4
image

**Comment by ASecondGuy** [comment]
> The about bbcode text is empty. Do I look at the right place?

I think the way the text is written to the label just does that. It displays right and that is important. 
To change the text use the text property of the About Node.

**Comment by Numenter** [comment]
> I think the way the text is written to the label just does that. It displays right and that is important. To change the text use the text property of the About Node.

Ah I looked at the wrong node. :P

**Comment by Numenter** [comment]
Im looking into the about:_process()
"_write_to_label" fails in "_notification" and "set_text" only in the beginning.
a "_write_to_label" in "_ready" fixs that.

Im not able to break it after this.
image

**Comment by ASecondGuy** [comment]
Last time I checked it also fails when the scene changes. Ready is not called in that case.

**Comment by RedstoneMedia** [comment]
> 1. There is a gap between header and body

To fix this just set the separation, of the root menu node to 0 (currently not overridden)

> the game info popup right section lost it’s white space

Set the VC stretch ratio under the InfoSection (In the game card) to 1 instead of 0.4 (Who even did that ?)

> the game info popup lost it’s shadow

- Replace the empty style box with a `StyleBoxFlat`.
- Unset draw center.
- Set the shadow size to 6 and the color to `#22000000`

I think these changes are so simple that I won't even have to make a PR for this.

**Comment by Numenter** [comment]
> Last time I checked it also fails when the scene changes. Ready is not called in that case.

I drilled some more and "set_text" is triggered on scene change.  ( text == "" and val == 'old text content' ).
So nothing changes at runtime, can be ignored.
It happens because text is an export and the scene value differs from default. Is some engine woodoo.

There is a comment that it fails in editor. I cant reproduce that.

**Comment by ASecondGuy** [comment]
> Set the VC stretch ratio under the InfoSection (In the game card) to 1 instead of 0.4 (Who even did that ?)

I did that. We both fixed the same problem at the same time from different sides. That overcompensated.

The first link had "" while the others didn't. That might be why it didn't work for you @b7g please confirm that it works now.

@Numenter thanks for looking into that. I'll try to fix it asap.

**Comment by b7g** [comment]
Yes, the link works now.

still … “refactoring of the scene tree.”:
aaa-1500

It’s awful.

The line spacing in the about tab is still missing too

**Comment by RedstoneMedia** [comment]
If you also mean the change of the "Spielzeit" location on the game card from bottom to top:
I actually think that it looks better when it's aligned on the top.

Your comparison does show some differences, however I think it's important to state that **not every** change is automatically a flaw (The user will only see one version and won't be able to nitpick the difference s like we are doing right now)

**Comment by b7g** [comment]
Yes, I agree.
Still it’s not just a “refactoring of the scene tree.” and feels like a downgrade visually.

To be clear: The playtime location is on the bottom with this PR and it looks terrible.

To merge this I will also require:
- that line-spacing in the about section is added again

It would be nice, if:
- the spacing after the logo badge would be added again
- the line spacing in the description of the game card and game card info popup is added again

I know it’s terrible hard for you to move your finger for a few pixels, but things were placed with consideration.
And you are breaking through that like an elephant in a flowerbed.

**Comment by RedstoneMedia** [comment]
Please keep your personal issues with others out of this thread, as it doesn't help the current discussion.
Also, who are you even referring to ?

Btw.: @ASecondGuy I opened a PR to fix the play time text location https://github.com/ASecondGuy/Suffragium/pull/8

**Comment by ASecondGuy** [comment]
Just as I finished it too...
Btw. what is the problem with the linespacing.
I don't know what is supposed to be wrong with that.

**Comment by b7g** [comment]
You refers to the PR

**Comment by ASecondGuy** [comment]
> You refers to the PR

Please be nice to the PR. It might not have a brain or a body or a consciousness or fingers it could move but it does have feelings

**Comment by RedstoneMedia** [comment]
> Just as I finished it too...

Bruh.

Ff this goes on we need to actually start to coordinate our actions (This requires a reliable and fast form of communication (Not GitHub or Discord)). I don't like wasting my time

**Comment by b7g** [comment]
Bildschirmfoto vom 2022-07-02 18-02-43

**Comment by RedstoneMedia** [comment]
Where does it even look like that?

**Comment by ASecondGuy** [comment]
It works on my machine ;)
image
Please send a real screenshot I can't look at your screen in case you didn't know.

**Comment by b7g** [comment]
It’s exaggerated…
I don’t expect that you (the PR) have any knowledge about Typography.

linespacing
left is this PR

**Comment by b7g** [comment]
thanks 🏈

**Comment by RedstoneMedia** [comment]
🏈

**Comment by ASecondGuy** [comment]
🏈

**Pull request merged**
